// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE5lmcVwH6igNYDFK0I6TRzQK_geqOPvU',
    appId: '1:568851041587:web:d07210e74e5c0d62030246',
    messagingSenderId: '568851041587',
    projectId: 'mausam-d02bd',
    authDomain: 'mausam-d02bd.firebaseapp.com',
    storageBucket: 'mausam-d02bd.appspot.com',
    measurementId: 'G-05EBTN26ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZKuuV35TqV7Z-pMtzuOc4nwoFKbINy8',
    appId: '1:568851041587:android:4132187c2cfba959030246',
    messagingSenderId: '568851041587',
    projectId: 'mausam-d02bd',
    storageBucket: 'mausam-d02bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDACGNfmb12JpjXiv_yVtrFa_S2CwzcNa4',
    appId: '1:568851041587:ios:d7e19392be2ecf4c030246',
    messagingSenderId: '568851041587',
    projectId: 'mausam-d02bd',
    storageBucket: 'mausam-d02bd.appspot.com',
    iosBundleId: 'com.example.uitask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDACGNfmb12JpjXiv_yVtrFa_S2CwzcNa4',
    appId: '1:568851041587:ios:987d55660abf0104030246',
    messagingSenderId: '568851041587',
    projectId: 'mausam-d02bd',
    storageBucket: 'mausam-d02bd.appspot.com',
    iosBundleId: 'com.example.uitask.RunnerTests',
  );
}
