// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqsE2F9fhk_Dct5B34MzMkYi3BMbwpN8I',
    appId: '1:233622925244:web:c5d9bef6fb2a85bee645b9',
    messagingSenderId: '233622925244',
    projectId: 'wawsim-f9f4a',
    authDomain: 'wawsim-f9f4a.firebaseapp.com',
    storageBucket: 'wawsim-f9f4a.appspot.com',
    measurementId: 'G-PFBRKGX2Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP1A2s2IhEMSRNzOz4JanpdldaNIg5-Sk',
    appId: '1:233622925244:android:53cde6a14fa0ba0fe645b9',
    messagingSenderId: '233622925244',
    projectId: 'wawsim-f9f4a',
    storageBucket: 'wawsim-f9f4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkQc8NWTF0JV9U2uzZ85G0FJ2kgpjYsNc',
    appId: '1:233622925244:ios:467b59ca44b21876e645b9',
    messagingSenderId: '233622925244',
    projectId: 'wawsim-f9f4a',
    storageBucket: 'wawsim-f9f4a.appspot.com',
    iosBundleId: 'net.hemish.wawsim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkQc8NWTF0JV9U2uzZ85G0FJ2kgpjYsNc',
    appId: '1:233622925244:ios:6c5fde659f88f0d6e645b9',
    messagingSenderId: '233622925244',
    projectId: 'wawsim-f9f4a',
    storageBucket: 'wawsim-f9f4a.appspot.com',
    iosBundleId: 'net.hemish.wawsim.RunnerTests',
  );
}
